version: "3.6"
services: 
  bwb: 
    image: biodepot/bwb-dev
    ports: 
      - "6080:6080"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${PWD}:/data"
    privileged: true
  service:
    image: biodepot/bwb-scheduling-service
    restart: always
    ports:
    - "8080:8080"
    command: service
  redis:
    image: redis
  agent:
    image: biodepot/local-agent
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp:/var/bwblogs
    entrypoint:
    - /bin/bash
    - /usr/src/app/docker_init.sh
    - agent
    - --api_url
    - http://service:8080
    - --hostname
    - agent
    - local-agent
    - --redis_host
    - redis
    - --redis_port
    - "6379"
  logger:
    image: gliderlabs/logspout
    restart: always
    volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "8088:80" 

